package com.example.trustshield

import android.util.Log
import com.example.trustshield.firebase.FirebaseService
import com.example.trustshield.models.LinkScan
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch

/**
 * LinkScanRecorder
 * Handles saving link analysis results to Firebase database
 * Runs asynchronously to avoid blocking notification processing
 */
class LinkScanRecorder(private val firebaseService: FirebaseService) {
    
    companion object {
        private const val TAG = "LINK_RECORDER"
    }
    
    /**
     * Record a link scan result to Firebase
     * Runs asynchronously in the background
     */
    fun recordLinkScan(
        url: String,
        host: String,
        riskLevel: LinkRiskLevel,
        verificationStatus: String?,
        verifiedBrand: String?,
        reasons: List<String>,
        sourceApp: String
    ) {
        GlobalScope.launch {
            try {
                val userId = firebaseService.getCurrentUserId()
                if (userId == null) {
                    Log.d(TAG, "No user logged in - skipping record")
                    return@launch
                }
                
                val linkScan = LinkScan(
                    scanId = "",  // Will be generated by Firebase
                    url = url,
                    host = host,
                    verdict = when (riskLevel) {
                        LinkRiskLevel.SAFE -> "SAFE"
                        LinkRiskLevel.SUSPICIOUS -> "SUSPICIOUS"
                        LinkRiskLevel.DANGEROUS -> "DANGEROUS"
                    },
                    riskLevel = when (riskLevel) {
                        LinkRiskLevel.SAFE -> "SAFE"
                        LinkRiskLevel.SUSPICIOUS -> "SUSPICIOUS"
                        LinkRiskLevel.DANGEROUS -> "DANGEROUS"
                    },
                    verificationStatus = verificationStatus,
                    verifiedBrand = verifiedBrand,
                    reasons = reasons,
                    sourceApp = sourceApp,
                    timestamp = System.currentTimeMillis(),
                    userAction = "ignored"  // Default - user can change later
                )
                
                val success = firebaseService.saveLinkScan(linkScan, userId)
                if (success) {
                    Log.d(TAG, "Link scan recorded: $host ($riskLevel)")
                } else {
                    Log.e(TAG, "Failed to record link scan")
                }
            } catch (e: Exception) {
                Log.e(TAG, "Error recording link scan: ${e.message}", e)
            }
        }
    }
}
